spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: uppick-product-service
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
            - id: uppick-main
              uri: ${MAIN_SERVICE_URL}
              predicates:
                - Path=/main/**
              filters:
                - StripPrefix=1
jwt:
  secret:
    key: ${JWT_KEY}