spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: uppick-member-service
              uri: ${MEMBER_SERVICE_URL}
              predicates:
                - Path=/api/v1/members/**, /api/v1/auth/**
            - id: uppick-main
              uri: ${MAIN_SERVICE_URL}
              predicates:
                - Path=/api/v1/products/**, /api/v1/auctions/**, /api/v1/categories/**, /api/v1/searching/**, /api/v1/ranking/**, /api/v1/notifications/**
jwt:
  secret:
    key: "VXBwaWNrUHJvamVjdFNlY3JldEtleUZvclRlc3RpbmdQdXJwb3NlczEyMzQ1Njc4OTA="