spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: uppick-product-service
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
            - id: uppick-main-service
              uri: ${MAIN_SERVICE_URL}
              predicates:
                - Path=/main/**
              filters:
                - StripPrefix=1
            - id: uppick-main-grpc-service
              uri: ${MAIN_GRPC_SERVICE_URL}
              predicates:
                - Path=/grpc/main/** 
              filters:
                - StripPrefix=2
jwt:
  secret:
    key: "VXBwaWNrUHJvamVjdFNlY3JldEtleUZvclRlc3RpbmdQdXJwb3NlczEyMzQ1Njc4OTA="
server:
  http2:
    enabled: true