version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uppick_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  uppick-api-gateway:
    build:
      context: .
      dockerfile: uppick-api-gateway/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      PRODUCT_SERVICE_URL: http://uppick-product-service:8080
      MAIN_SERVICE_URL: http://uppick-main:8080
    ports:
      - "8000:8000"
    restart: on-failure

  uppick-product-service:
    build:
      context: .
      dockerfile: uppick-product-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:mysql://mysql:3306/uppick_db
      DB_USER: user
      DB_PASS: password
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  uppick-main-service:
    build:
      context: .
      dockerfile: uppick-main-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:mysql://mysql:3306/uppick_db
      DB_USER: user
      DB_PASS: password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql_data:
