version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uppick_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  uppick-member-service:
    build:
      context: ./uppick-member-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/uppick_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: user
      DB_PASS: password
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  uppick-main:
    build:
      context: ./uppick-main
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/uppick_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: user
      DB_PASS: password
      AWS_REGION: ap-northeast-2
      S3_BUCKET_NAME: my-dev-bucket
      JWT_KEY: dev-secret-key
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql_data:
