spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${S3_BUCKET_NAME}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations:
      - classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8080
jwt:
  secret:
    key: ${JWT_KEY}